<?php

/**
 * Implementation of hook_fontyourface_info().
 */
function local_fonts_fontyourface_info() {

  return array(
    'name' => t('Local Fonts'),
    'url' => 'http://drupal.org/project/fontyourface#local'
  );

} // local_fonts_fontyourface_info

/**
 * Implementation of hook_menu().
 */
function local_fonts_menu() {

  $items = array();

  $items['admin/settings/fontyourface/local_fonts'] = array(
    'title' => 'Import Local Font',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('local_fonts_add_fontface'),
    'access arguments' => array('administer @font-your-face'),
  );

  $items['admin/build/themes/fontyourface/local_fonts/delete/%'] = array(
    'title' => 'Delete Local Font',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('local_fonts_delete_fontface', 6),
    'access arguments' => array('administer @font-your-face'),
    'type' => MENU_CALLBACK,
  );

  return $items;

} // local_fonts_menu

/**
 * Implementation of hook_form_alter().
 */
function local_fonts_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'fontyourface_settings_form') {

    // Replace button with a link to the custom font form.

    $form['providers']['local_fonts_import']['import'] = array(
      '#type' => 'markup',
      '#value' => l(t('Import Local Font'), 'admin/settings/fontyourface/local_fonts'),
    );

  } // if
  elseif ($form_id == 'fontyourface_admin_edit_form') {

    // Add delete button.

    $form['buttons']['delete'] = array(
      '#type' => 'submit',
      '#value' => t('Delete font record'),
      '#submit' => array('local_fonts_delete_button_submit'),
    );

  } // elseif

} // local_fonts_form_fontyourface_settings_form_alter

/**
 * Redirect to delete confirmation form.
 */
function local_fonts_delete_button_submit($form, &$form_state) {

  $destination = '';
  if (isset($_REQUEST['destination'])) {
    $destination = drupal_get_destination();
    unset($_REQUEST['destination']);
  }
  $form_state['redirect'] = array('admin/build/themes/fontyourface/local_fonts/delete/' . $form['fid']['#value'], $destination);

} // local_fonts_delete_button_submit

/**
 * Form for submitting a local font.
 */
function local_fonts_add_fontface($form_state) {

  $form = array();

  $form['local_fonts']['information'] = array(
    '#type' => 'fieldset',
    '#title' => t('Font Information'),
    '#collapsible' => FALSE,
  );

  $form['local_fonts']['information']['css_family'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS Font Family'),
    '#required' => TRUE,
  );

  $form['local_fonts']['information']['css_style'] = array(
    '#type' => 'select',
    '#title' => t('CSS Font Style'),
    '#options' => array(
      'normal' => t('Normal'),
      'italic' => t('Italic'),
      'oblique' => t('Oblique'),
    ),
    '#required' => TRUE,
  );

  $form['local_fonts']['information']['css_weight'] = array(
    '#type' => 'select',
    '#title' => t('CSS Font Weight'),
    '#options' => array(
      'normal' => t('Normal'),
      'bold' => t('Bold'),
      'bolder' => t('Bolder'),
      'lighter' => t('Lighter'),
      '100' => t('100'),
      '200' => t('200'),
      '300' => t('300'),
      '400' => t('400'),
      '500' => t('500'),
      '600' => t('600'),
      '700' => t('700'),
      '800' => t('800'),
      '900' => t('900'),
    ),
    '#required' => TRUE,
  );

  $form['local_fonts']['upload']['eot'] = array(
    '#type' => 'file',
    '#title' => t('EOT font file'),
    '#description' => t('Embedded Open Type. This format is supported by IE 5-8.'),
  );

  $form['local_fonts']['upload']['ttf'] = array(
    '#type' => 'file',
    '#title' => t('TTF font file'),
    '#description' => t('Raw TrueType file, designed to look good on-screen. This format is supported by Webkit/Safari 3.1+, Safari Mobile iOS 4.2+, Opera 10+, Mozilla/Firefox 3.5+, and Chrome 4+'),
  );

  $form['local_fonts']['upload']['woff'] = array(
    '#type' => 'file',
    '#title' => t('WOFF font file'),
    '#description' => t('Web-only font format that uses gzip compression. This format is supported by IE9+, FF3.6+, Chrome 5+.')
  );

  $form['local_fonts']['upload']['svg'] = array(
    '#type' => 'file',
    '#title' => t('SVG font file'),
    '#description' => t('An XML format required by iOS devices before version 4.2. Currently supported by iOS 4.1 and below, and Opera 10+.')
  );

  $form = confirm_form($form, t('Import Local Font'), 'admin/settings/fontyourface', '');
  $form['#attributes'] = array('enctype' => 'multipart/form-data');

  return $form;

} // local_fonts_add_fontface

/**
 * Implementation of hook_form_validate().
 */
function local_fonts_add_fontface_validate($form, &$form_state) {

  // Ensure a font family with the same results does not exist in the database.

  $values = $form_state['values'];
  $font_path = strtr(preg_replace('#[^a-zA-Z0-9]+#', ' ', $values['css_family']), ' ', '_');
  $font_style = $values['css_style'];
  $font_weight = $values['css_weight'];
  $local_fonts_directory = dirname($_SERVER['SCRIPT_FILENAME']) . '/' . file_directory_path() . '/fontyourface/local_fonts';
  $destination_directory = $local_fonts_directory . '/' . $font_path;

  $file_uploaded = FALSE;

  if (
    (file_check_directory($local_fonts_directory, FILE_CREATE_DIRECTORY)) &&
    (file_check_directory($destination_directory, FILE_CREATE_DIRECTORY))
  ) {

    // Validate the files against their extension

    $files = $_FILES['files']['name'];

    foreach ($files as $key => $filename) {

      $file_object = new stdClass;
      $file_object->filename = $filename;

      if (!empty($file_object->filename)) {

        $validation = file_validate_extensions($file_object, $key);

        if (is_array($validation) && count($validation) > 0) {
          form_set_error($key, implode(', ', $validation));
        } // if
        else {
          $file_uploaded = TRUE;
        } // else

      } // if

    } // foreach

  } // if
  else {
    form_set_error('files', t('Error creating file directory.'));
  } // else

  if (!$file_uploaded) {
    form_set_error('files', t('Upload at least one font file to go with the font family.'));
  } // if

} // local_fonts_add_fontface_validate

/**
 * Implementation of hook_form_submit().
 */
function local_fonts_add_fontface_submit($form, &$form_state) {

  $values = $form_state['values'];
  $font_path = strtr(preg_replace('#[^a-zA-Z0-9]+#', ' ', $values['css_family']), ' ', '_') . '-' . $values['css_style'] . '-' . $values['css_weight'];
  $font_family = $values['css_family'];
  $font_style = $values['css_style'];
  $font_weight = $values['css_weight'];
  $local_fonts_directory = dirname($_SERVER['SCRIPT_FILENAME']) . '/' . file_directory_path() . '/fontyourface/local_fonts';
  $destination_directory = $local_fonts_directory . '/' . $font_path;
  $destination_css_file = $destination_directory . '/stylesheet.css';
  $css_path = file_directory_path() .'/fontyourface/local_fonts/' . $font_path . '/stylesheet.css';

  $files = $_FILES['files']['name'];

  $combined_sources = array();
  $src = '';

  if (
    (file_check_directory($local_fonts_directory, FILE_CREATE_DIRECTORY)) &&
    (file_check_directory($destination_directory, FILE_CREATE_DIRECTORY))
  ) {

    foreach ($files as $key => $filename) {

      $format = $key;

      // Everything but TTF matches the extension.

      if ($format == 'ttf') {
        $format = 'truetype';
      } // if

      if (!empty($filename)) {

        if ($file = file_save_upload($key, array(), $destination_directory . '/' . $filename . '.tmp', FILE_EXISTS_REPLACE)) {

          // Copy the temporary file to permanent location.

          if (file_copy($file, $destination_directory . '/' . $filename, FILE_EXISTS_REPLACE)) {

            file_set_status($file, FILE_STATUS_PERMANENT);

            if ($format == 'eot') {

              // EOT goes on its own line and doesn't take a format.
              // Because IE is a "special needs" browser.

              $src .= '  src: url("' . $file->filename . '");' . "\n";

            } // if
            elseif ($format == 'svg') {

              // Get the font ID from the SVG file.

              $svg = file_get_contents($file->filepath);
              $hash = '';

              if (preg_match('#<font([^>]+)>#i', $svg, $font_tag_match)) {

                if (preg_match('#id="([^"]+)"#i', $font_tag_match[1], $id_match)) {
                  $hash = $id_match[1];
                } // if
                elseif (preg_match("#id='([^']+)'#i", $font_tag_match[1], $id_match)) {
                  $hash = $id_match[1];
                } // elseif

              } // if

              $url = $file->filename . '#' . $hash;
              $combined_sources[] = 'url("' . $url . '") format("' . $format . '")';

            } // elseif
            else {

              $combined_sources[] = 'url("' . $file->filename . '") format("' . $format . '")';

            } // else

          } // if

        } // if

      } // if

    } // foreach

    if (count($combined_sources) > 0) {

      // Add a fake local font name first to prevent name conflicts with local fonts.

      $src .= '  src: local("Ä¿– ´¿Ÿ¨ÄŒŽ"), ' . implode(', ', $combined_sources) . ';' . "\n";

    } // if

    $generated_css = '@font-face {' . "\n";
    $generated_css .= "  font-family: '" . $font_family . "';" . "\n";
    $generated_css .= $src;
    $generated_css .= '  font-style: ' . $font_style . ';' . "\n";
    $generated_css .= '  font-weight: ' . $font_weight . ';' . "\n";
    $generated_css .= '}' . "\n";

    $css_file = file_save_data($generated_css, $destination_css_file);

    $local_font = new stdClass;
    $local_font->name = $font_family . ' ' . $font_style . ' ' . $font_weight;
    $local_font->url = 'http://localhost/#' . md5($local_font->name);
    $local_font->css_family = "'" . $font_family . "'";
    $local_font->css_style = $font_style;
    $local_font->css_weight = $font_weight;
    $local_font->provider = 'local_fonts';
    $local_font->metadata = serialize(array('path' => $css_path));

    fontyourface_save_font($local_font);

    drupal_set_message(t('@font added.', array('@font' => $font_family)));

  } // if

  drupal_goto('admin/settings/fontyourface');

} // local_fonts_add_fontface_submit

/**
 * Form for deleting a local font.
 */
function local_fonts_delete_fontface($form_state, $fid) {

  $font = fontyourface_get_font($fid);

  $form = array(
    'fid' => array(
      '#type' => 'value',
      '#value' => $fid,
    ),
    'confirm' => array(
      '#type' => 'fieldset',
      '#title' => t('Confirm delete of @title?', array('@title' => $font->name)),
      array(
        '#type' => 'submit',
        '#value' => 'Delete font record',
      ),
      array(
        '#type' => 'submit',
        '#value' => 'Cancel',
      ),
    ),
  );

  return $form;

} // local_fonts_delete_fontface

function local_fonts_delete_fontface_submit($form, &$form_state) {

  if ($form['#post']['op'] == t('Cancel')) {

    drupal_goto('admin/build/themes/fontyourface/edit/' . $form['fid']['#value']);

  } // if
  else {

    $font = fontyourface_get_font($form['fid']['#value']);
    fontyourface_delete_font($font);

    drupal_set_message(t('@font deleted.', array('@font' => $font->name)));
    drupal_goto('admin/build/themes/fontyourface');

  } // else

} // local_fonts_delete_fontface_submit

/**
 * Implements hook_fontyourface_delete().
 * Removes directory of deleted font.
 */
function local_fonts_fontyourface_delete($font) {

  $metadata = unserialize($font->metadata);

  $directory = dirname($metadata['path']);

  // Delete all the files.

  $files = scandir($directory);

  foreach ($files as $file) {

    if ($file != '.' && $file != '..') {
      unlink($directory . '/' . $file);
    } // if

  } // foreach

  // Delete the directory.

  rmdir($directory);

  return TRUE;

} // local_fonts_fontyourface_delete

/**
 * Implements hook_fontyourface_preview().
 */
function local_fonts_fontyourface_preview($font) {

  return '<span style="' . fontyourface_font_css($font) . ' font-size: 24px;">' . $font->name . '</span>';

} // local_fonts_fontyourface_preview

/**
 * Implements hook_fontyourface_view().
 */
function local_fonts_fontyourface_view($font, $text) {

  $output = '';
  $sizes = array(32, 24, 18, 14, 12, 10);

  foreach ($sizes as $size) {

    $output .= '<div style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</div>';

  } // foreach

  return $output;

} // local_fonts_fontyourface_view

/**
 * Implements template_preprocess_page().
 */
function local_fonts_preprocess_page(&$vars) {

  if (!empty($vars['fontyourface'])) {

    foreach ($vars['fontyourface'] as $used_font) {

      if ($used_font->provider == 'local_fonts') {
        $metadata = unserialize($used_font->metadata);
        fontyourface_add_css_in_preprocess($vars, $metadata['path'], FALSE);
      } // if

    } // foreach

  } // if

} // local_fonts_preprocess_page
