<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function cod_events_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'type' => 'event',
  'language' => '',
  'uid' => '4',
  'status' => '1',
  'created' => '1316471187',
  'changed' => '1318518155',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'DrupalCampNYC 10',
  'body' => 'Register to attend DrupalCampNYC 10 at John Jay College on Saturday, December 10th, 2011',
  'teaser' => 'Register to attend DrupalCampNYC 10 at John Jay College on Saturday, December 10th, 2011',
  'log' => 'Force a new revision for uuid',
  'revision_timestamp' => '1318518155',
  'format' => '1',
  'name' => 'FatherShawn',
  'picture' => 'sites/default/files/user_pictures/picture-4.jpg',
  'data' => 'a:4:{s:13:"form_build_id";s:37:"form-6952dea8017db635329ec02e56008264";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'model' => 'DC10',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '20.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '1',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'event/drupalcampnyc-10',
  'field_dates' => array(
    '0' => array(
      'value' => NULL,
      'value2' => NULL,
      'timezone' => 'America/New_York',
      'timezone_db' => 'UTC',
      'date_type' => 'date',
    ),
  ),
  'field_image_cache' => array(),
  'signup' => 1,
  'signup_forwarding_email' => '',
  'signup_send_confirmation' => '1',
  'signup_confirmation_email' => 'Hello %user_name,

Thanks so much for registering to attend DrupalCampNYC 10 at John Jay College on December 10, 2011. This email is your confirmation that you are registered.

Next steps:
Submit a session proposal at http://www.drupalcampnyc.org/node/add/session
If you\'ve got some fantastic Drupally knowledge you\'d like to share, let\'s hear it! Sessions will be accepted for Beginner, Intermediate, and Advanced audiences, and the tracks for this camp are Development, Site building, Presentation, Business & end users, and Sysadmin & performance. Check out How can I submit a session? (http://www.drupalcampnyc.org/about/faq/how-can-i-submit-session) for tips on putting together your proposal.

Keep in touch! We\'re on Twitter , Facebook , and of course the NYC Drupal Group on groups.drupal.org .
Tell your friends! The official hashtag for DrupalCampNYC 10 is #DCNYC10. Tweet about the Camp and let the world know you\'ll be there!
See you at DrupalCamp!

DCNYC10 Organizing Team

If you are unable to attend, please cancel your attendance at %cancel_signup_url so another can have your place.',
  'signup_send_reminder' => '0',
  'signup_reminder_days_before' => '0',
  'signup_reminder_email' => '',
  'signup_close_signup_limit' => '400',
  'signup_status' => '1',
  'signup_user_reg_form' => '0',
  'signup_total' => '0',
  'signup_effective_total' => NULL,
  'uc_order_product_id' => FALSE,
  'last_comment_timestamp' => '1316471187',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '62bca67e-f5ac-11e0-a4e0-46138b83f027',
  'revision_uuid' => '62bcb75e-f5ac-11e0-a4e0-46138b83f027',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-09-19 18:26:27 -0400',
);
  return $nodes;
}
