<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function cod_sponsor_sales_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'type' => 'sponsorship',
  'language' => '',
  'uid' => '4',
  'status' => '1',
  'created' => '1318518920',
  'changed' => '1318727903',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'Upgrade Sponsor',
  'body' => 'Sponsorships can also be upgraded to the Premium level for an additional commitment of $250 or more.  As a Premium sponsor, you receive the additional benefits of:
<ul>
<li>Company logo on the poster boards and easels to be located on every floor.</li> <li>Premium sponsor logos will be larger and in a section called “Premium Sponsors” on the top section of the signage.</li>
<li>Logo displayed in a spotlight section of the web site’s home page, as well as in the sponsor section.</li>
<li>Logos projected in the opening ‘Thank You’ slides in the plenary session.</li>
<li>Two Camp tickets for use by your staff.</li>
<li>Option to place SWAG on the SWAG table at registration.</li>
</ul>',
  'teaser' => 'Sponsorships can also be upgraded to the Premium level for an additional commitment of $250 or more.  As a Premium sponsor, you receive the additional benefits of:
<ul>
<li>Company logo on the poster boards and easels to be located on every floor.</li> <li>Premium sponsor logos will be larger and in a section called “Premium Sponsors” on the top section of the signage.</li>
<li>Logo displayed in a spotlight section of the web site’s home page, as well as in the sponsor section.</li>
<li>Logos projected in the opening ‘Thank You’ slides in the plenary session.</li>',
  'log' => '',
  'revision_timestamp' => '1318727903',
  'format' => '1',
  'name' => 'FatherShawn',
  'picture' => 'sites/default/files/user_pictures/picture-4.jpg',
  'data' => 'a:4:{s:13:"form_build_id";s:37:"form-6952dea8017db635329ec02e56008264";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'model' => '03-upgrade-dcny10',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '250.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '1',
  'unique_hash' => 'b32e38be86b71d9346ab544157533d72',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'content/upgrade-sponsor',
  'field_sponsorship_level' => array(
    '0' => array(
      'value' => 'premium',
    ),
  ),
  'signup' => 0,
  'uc_order_product_id' => FALSE,
  'last_comment_timestamp' => '1318518920',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '2a70c2e4-f5ae-11e0-a4e0-46138b83f027',
  'revision_uuid' => '2a70c76c-f5ae-11e0-a4e0-46138b83f027',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-13 11:15:20 -0400',
);
  $nodes[] = array(
  'type' => 'sponsorship',
  'language' => '',
  'uid' => '4',
  'status' => '1',
  'created' => '1318453648',
  'changed' => '1318518241',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '0',
  'title' => 'Premium Sponsor',
  'body' => '<em>Benefits:</em>
<ul>
<li>Company logo on the poster boards and easels to be located on every floor.</li> <li>Premium sponsor logos will be larger and in a section called “Premium Sponsors” on the top section of the signage.</li>
<li>Logo displayed in a spotlight section of the web site’s home page, as well as in the sponsor section.</li>
<li>Logos projected in the opening ‘Thank You’ slides in the plenary session.</li>
<li>Two Camp tickets for use by your staff.</li>
<li>Option to place SWAG on the SWAG table at registration.</li>
</ul>',
  'teaser' => '<em>Benefits:</em>
<ul>
<li>Company logo on the poster boards and easels to be located on every floor.</li> <li>Premium sponsor logos will be larger and in a section called “Premium Sponsors” on the top section of the signage.</li>
<li>Logo displayed in a spotlight section of the web site’s home page, as well as in the sponsor section.</li>
<li>Logos projected in the opening ‘Thank You’ slides in the plenary session.</li>
<li>Two Camp tickets for use by your staff.</li>
<li>Option to place SWAG on the SWAG table at registration.</li>
</ul>',
  'log' => 'New version to force uuid',
  'revision_timestamp' => '1318518241',
  'format' => '1',
  'name' => 'FatherShawn',
  'picture' => 'sites/default/files/user_pictures/picture-4.jpg',
  'data' => 'a:4:{s:13:"form_build_id";s:37:"form-6952dea8017db635329ec02e56008264";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'model' => '01-premium-dcny10',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '500.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '1',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'sponsors/premium-sponsor',
  'field_sponsorship_level' => array(
    '0' => array(
      'value' => 'premium',
    ),
  ),
  'signup' => 0,
  'uc_order_product_id' => FALSE,
  'last_comment_timestamp' => '1318453648',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '68898ac4-f5aa-11e0-a4e0-46138b83f027',
  'revision_uuid' => '598c2e18-f5ab-11e0-a4e0-46138b83f027',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-12 17:07:28 -0400',
);
  $nodes[] = array(
  'type' => 'sponsorship',
  'language' => '',
  'uid' => '4',
  'status' => '1',
  'created' => '1318518644',
  'changed' => '1318728454',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'Carryover Sponsor',
  'body' => 'Sponsorship for DCNYC9 has carried over to DCNYC10.  As a carryover sponsor, you will receive:
<ul><li>Company logo displayed on the general sponsor page of the web site</li>
<li>Logo displayed on Camp signage beneath Premium Sponsor logos</li>
<li>Logo projected in the opening ‘Thanks’ slides in the plenary session, beneath Premium Sponsor logos</li>
<li>One Camp ticket for use by your staff</li>
<li>Option to place SWAG on the SWAG table at registration.</li></ul>',
  'teaser' => 'Sponsorship for DCNYC9 has carried over to DCNYC10.  As a carryover sponsor, you will receive:
<ul><li>Company logo displayed on the general sponsor page of the web site</li>
<li>Logo displayed on Camp signage beneath Premium Sponsor logos</li>
<li>Logo projected in the opening ‘Thanks’ slides in the plenary session, beneath Premium Sponsor logos</li>
<li>One Camp ticket for use by your staff</li>
<li>Option to place SWAG on the SWAG table at registration.</li></ul>',
  'log' => '',
  'revision_timestamp' => '1318728454',
  'format' => '1',
  'name' => 'FatherShawn',
  'picture' => 'sites/default/files/user_pictures/picture-4.jpg',
  'data' => 'a:4:{s:13:"form_build_id";s:37:"form-6952dea8017db635329ec02e56008264";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'model' => '04-carryover-dcny10',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '0.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '1',
  'unique_hash' => '362725f51eed99a3e8a65caa0511d05c',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'sponsors/carryover-sponsor',
  'field_sponsorship_level' => array(
    '0' => array(
      'value' => 'sponsor',
    ),
  ),
  'signup' => 0,
  'uc_order_product_id' => FALSE,
  'last_comment_timestamp' => '1318518644',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '85cd7da4-f5ad-11e0-a4e0-46138b83f027',
  'revision_uuid' => '85cd8222-f5ad-11e0-a4e0-46138b83f027',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-13 11:10:44 -0400',
);
  $nodes[] = array(
  'type' => 'sponsorship',
  'language' => '',
  'uid' => '4',
  'status' => '1',
  'created' => '1318453848',
  'changed' => '1318518282',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '0',
  'title' => 'General Sponsor',
  'body' => '<em>Benefits:</em>
<ul><li>Company logo displayed on the general sponsor page of the web site.</li>
<li>Logo displayed on Camp signage beneath Premium Sponsor logos.</li>
<li>Logo projected in the opening ‘Thanks’ slides in the plenary session, beneath Premium Sponsor logos.</li>
<li>One Camp ticket for use by your staff.</li>
<li>Option to place SWAG on the SWAG table at registration.</li>',
  'teaser' => '<em>Benefits:</em>
<ul><li>Company logo displayed on the general sponsor page of the web site.</li>
<li>Logo displayed on Camp signage beneath Premium Sponsor logos.</li>
<li>Logo projected in the opening ‘Thanks’ slides in the plenary session, beneath Premium Sponsor logos.</li>
<li>One Camp ticket for use by your staff.</li>
<li>Option to place SWAG on the SWAG table at registration.</li>',
  'log' => 'New version to force uuid',
  'revision_timestamp' => '1318518282',
  'format' => '1',
  'name' => 'FatherShawn',
  'picture' => 'sites/default/files/user_pictures/picture-4.jpg',
  'data' => 'a:4:{s:13:"form_build_id";s:37:"form-6952dea8017db635329ec02e56008264";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'model' => '02-sponsor-dcny10',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '250.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '1',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'sponsors/general-sponsor',
  'field_sponsorship_level' => array(
    '0' => array(
      'value' => 'sponsor',
    ),
  ),
  'signup' => 0,
  'uc_order_product_id' => FALSE,
  'last_comment_timestamp' => '1318453848',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => 'a456d354-f5aa-11e0-a4e0-46138b83f027',
  'revision_uuid' => '964a3b7e-f5ab-11e0-a4e0-46138b83f027',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-12 17:10:48 -0400',
);
  $nodes[] = array(
  'type' => 'product',
  'language' => '',
  'uid' => '4',
  'status' => '1',
  'created' => '1318452946',
  'changed' => '1318517882',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '0',
  'title' => 'Support',
  'body' => 'Supporters make a donation to DrupalCampNYC that is less than $250. ',
  'teaser' => 'Supporters make a donation to DrupalCampNYC that is less than $250. ',
  'log' => 'New version to force uuid',
  'revision_timestamp' => '1318517882',
  'format' => '1',
  'name' => 'FatherShawn',
  'picture' => 'sites/default/files/user_pictures/picture-4.jpg',
  'data' => 'a:4:{s:13:"form_build_id";s:37:"form-6952dea8017db635329ec02e56008264";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'model' => 'dcny10-support',
  'list_price' => '0.00000',
  'cost' => '0.00000',
  'sell_price' => '0.00000',
  'weight' => '0',
  'weight_units' => 'lb',
  'length' => '0',
  'width' => '0',
  'height' => '0',
  'length_units' => 'in',
  'pkg_qty' => '1',
  'default_qty' => '1',
  'unique_hash' => '',
  'ordering' => '0',
  'shippable' => '0',
  'path' => 'sponsors/support',
  'field_image_cache' => array(),
  'signup' => 0,
  'uc_order_product_id' => FALSE,
  'last_comment_timestamp' => '1318452946',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => 'c008ea64-f5ab-11e0-a4e0-46138b83f027',
  'revision_uuid' => 'bbb3ac9e-f667-11e0-8817-0016e3f4e63e',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-12 16:55:46 -0400',
);
  return $nodes;
}
