<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function about_dcny_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'type' => 'page',
  'language' => '',
  'uid' => '6',
  'status' => '1',
  'created' => '1317586459',
  'changed' => '1317851665',
  'comment' => '2',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '6',
  'title' => 'The Camp',
  'body' => '<p>DrupalCamp NYC has a long history of bringing together New York City-area Drupalistas of all stripes.  Our 10th camp continues that tradition, striving to engage and educate across the spectrum of Drupal professionals.</p>
<p>Who does this spectrum include?</p>
	<ul>
	<li>All skill levels, from explorer to expert</li>
		<li>Developers, themers, and site builders</li>

		<li>Designers</li>
		<li>Project Managers and Functional Analysts</li>
		<li>Site managers, community managers, and content editors</li>
		<li>Project owners and end users from all sectors, including corporate, non-profit, government, and education</li>
		<li>Anyone wondering if Drupal is the right tool or new skill for them</li>
	</ul>
	<p>The New York City Drupal community is a collection of friendly people that are eager to accept newcomers, who are always welcome to any event.  Regardless of your experience with Drupal, or lack thereof, we warmly invite you to join us for DrupalCampNYC 10.</p>
	<p>Get know Drupal, grow your skills {link to schedule when available}, share your wisdom {link to session submission page}, or just make some Drupally new friends.</p>
	<p>See you there!</p>


',
  'teaser' => '<p>DrupalCamp NYC has a long history of bringing together New York City-area Drupalistas of all stripes.  Our 10th camp continues that tradition, striving to engage and educate across the spectrum of Drupal professionals.</p>
<p>Who does this spectrum include?</p>',
  'log' => '',
  'revision_timestamp' => '1317851665',
  'format' => '1',
  'name' => 'Amy Cham',
  'picture' => '',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-95351b7365a0fe5fe1c86ea51cc8e52e";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'path' => 'about/camp',
  'signup' => 0,
  'last_comment_timestamp' => '1317586459',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '1c38f6f2-ed33-11e0-9f00-3d6a5b8caab1',
  'revision_uuid' => '1c38ff12-ed33-11e0-9f00-3d6a5b8caab1',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-02 16:14:19 -0400',
  'field_illustration' => array(),
);
  $nodes[] = array(
  'type' => 'page',
  'language' => '',
  'uid' => '6',
  'status' => '1',
  'created' => '1317586583',
  'changed' => '1317747360',
  'comment' => '2',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'Venue',
  'body' => 'This is a stub waiting for content',
  'teaser' => 'This is a stub waiting for content',
  'log' => '',
  'revision_timestamp' => '1317747360',
  'format' => '1',
  'name' => 'Amy Cham',
  'picture' => '',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-95351b7365a0fe5fe1c86ea51cc8e52e";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'path' => 'about/venue',
  'signup' => 0,
  'last_comment_timestamp' => '1317586583',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '66450c18-ed33-11e0-9f00-3d6a5b8caab1',
  'revision_uuid' => '6645149c-ed33-11e0-9f00-3d6a5b8caab1',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-02 16:16:23 -0400',
  'field_illustration' => array(),
);
  $nodes[] = array(
  'type' => 'page',
  'language' => '',
  'uid' => '6',
  'status' => '1',
  'created' => '1317586632',
  'changed' => '1317747376',
  'comment' => '2',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'Getting There',
  'body' => 'This is a stub waiting for content',
  'teaser' => 'This is a stub waiting for content',
  'log' => '',
  'revision_timestamp' => '1317747376',
  'format' => '1',
  'name' => 'Amy Cham',
  'picture' => '',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-95351b7365a0fe5fe1c86ea51cc8e52e";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'path' => 'about/getting-there',
  'signup' => 0,
  'last_comment_timestamp' => '1317586632',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '8393c46c-ed33-11e0-9f00-3d6a5b8caab1',
  'revision_uuid' => '8393cc6e-ed33-11e0-9f00-3d6a5b8caab1',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-02 16:17:12 -0400',
  'field_illustration' => array(),
);
  $nodes[] = array(
  'type' => 'page',
  'language' => '',
  'uid' => '6',
  'status' => '1',
  'created' => '1317586305',
  'changed' => '1317747416',
  'comment' => '2',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'About',
  'body' => 'This a stub waiting for content.',
  'teaser' => 'This a stub waiting for content.',
  'log' => '',
  'revision_timestamp' => '1317747416',
  'format' => '1',
  'name' => 'Amy Cham',
  'picture' => '',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-95351b7365a0fe5fe1c86ea51cc8e52e";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-ee349b50b69f7c304a8a9c4705b4e8fb";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'path' => 'about',
  'signup' => 0,
  'last_comment_timestamp' => '1317586305',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => 'c0f1f910-ed32-11e0-9f00-3d6a5b8caab1',
  'revision_uuid' => 'c0f20126-ed32-11e0-9f00-3d6a5b8caab1',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-02 16:11:45 -0400',
  'field_illustration' => array(),
);
  $nodes[] = array(
  'type' => 'page',
  'language' => '',
  'uid' => '6',
  'status' => '1',
  'created' => '1317586737',
  'changed' => '1317855169',
  'comment' => '2',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '6',
  'title' => 'Drupal in NYC',
  'body' => '<p>As befits a city with one of the (if not <em>the</em>) most heterogeneous populaces in the world, the New York City Drupal community consists of Drupal professionals from a vast array of sectors, interests, and experience levels.</p>
As a center for commerce, non-profit, and higher education, NYC offers a plethora of opportunities for growth in terms of both implementations and talent. Drupal can be found in use at:
	<ul>
	<li>Major publishing firms</li>
		<li>Television networks</li>

		<li>Top-tier universities</li>
		<li>NGOs</li>
		<li>Educational Institutions</li>
		<li>Financial institutions</li>
		<li>Fashion and beauty sites</li>
		<li>Major content networks</li>

		<li>Non-profits large and small</li>
		<li>Startups</li>
	</ul>
	<p>The NYC Drupal users group is similarly expansive, with active members at all skill levels and representing developers, themers, editors, designers and builders. Inasmuch as we are different in our skills, interests, and sectors, we are all united in a common love for the Drupal platform, and a shared desire to keep the community a welcoming place for both new and established Drupalistas.</p>
	<p>As of this writing, the NYC Drupal user group is the largest regional group on groups.Drupal.org (GDO), with 1807 members. NYC DrupalCamps sell out fast, and our monthly meetups and Drupal drinks events are regularly standing room only.</p>
<p>Want to join in the fun and get to know us better?</p>
	<ul>
	<li><a href=\'http://groups.drupal.org/nyc\' target=\'_blank\'>Join our group on GDO</a></li>
		<li><a href=\'http://twitter.com/#!/drupalnyc\' target=\'_blank\'>Follow us on Twitter</a></li>
		<li>Hang out with us in IRC at #drupal-nyc</li>
	</ul>',
  'teaser' => '<p>As befits a city with one of the (if not <em>the</em>) most heterogeneous populaces in the world, the New York City Drupal community consists of Drupal professionals from a vast array of sectors, interests, and experience levels.</p>',
  'log' => '',
  'revision_timestamp' => '1317855169',
  'format' => '1',
  'name' => 'Amy Cham',
  'picture' => '',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-95351b7365a0fe5fe1c86ea51cc8e52e";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'path' => 'about/drupalnyc',
  'signup' => 0,
  'last_comment_timestamp' => '1317586737',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => 'c1e1c142-ed33-11e0-9f00-3d6a5b8caab1',
  'revision_uuid' => 'c1e1c8ea-ed33-11e0-9f00-3d6a5b8caab1',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-02 16:18:57 -0400',
  'field_illustration' => array(),
);
  return $nodes;
}
