<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function cod_front_page_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'type' => 'page',
  'language' => '',
  'uid' => '6',
  'status' => '1',
  'created' => '1317828424',
  'changed' => '1317828424',
  'comment' => '2',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '4',
  'title' => 'Home',
  'body' => 'This page is waiting for content.',
  'teaser' => 'This page is waiting for content.',
  'log' => '',
  'revision_timestamp' => '1317828424',
  'format' => '1',
  'name' => 'Amy Cham',
  'picture' => '',
  'data' => 'a:5:{s:6:"signup";a:1:{i:5;i:1;}s:13:"form_build_id";s:37:"form-95351b7365a0fe5fe1c86ea51cc8e52e";s:7:"contact";i:1;s:14:"picture_delete";s:0:"";s:14:"picture_upload";s:0:"";}',
  'path' => 'home',
  'signup' => 0,
  'last_comment_timestamp' => '1317828424',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '7a955198-ef66-11e0-9f00-3d6a5b8caab1',
  'revision_uuid' => '7a9559e0-ef66-11e0-9f00-3d6a5b8caab1',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-10-05 11:27:04 -0400',
  'field_illustration' => array(),
);
  return $nodes;
}
